name: 'Terragrunt GitHub Actions'
on:
    pull_request:
      types:
        - opened
        - reopened
        - labeled
        - synchronize
        - closed
      branches:
        - main

jobs:
  checks:
    name: Terraform checks
    if: ${{ github.event.pull_request.merged == false }}
    uses: DulaniG/Reusable-workflows/.github/workflows/terragrunt.yaml@main
    with:
      Terraform_version: 1.5.7
      Terragrunt_version: 0.53.2
      Working_Directory: envs/dev
      AWS_region: us-east-1

  plan:
    name: Terraform plan
    if: ${{ github.event.pull_request.merged == false }}
    uses: DulaniG/Reusable-workflows/.github/workflows/terragrunt.yaml@main
    needs: [ checks ]
    with:
      Terraform_version: 1.5.7
      Terragrunt_version: 0.53.2
      Working_Directory: envs/dev
      AWS_region: us-east-1

  deploy:
    name: Terraform apply
    if: ${{ github.event.pull_request.merged == true }}
    uses: DulaniG/Reusable-workflows/.github/workflows/terragrunt.yaml@main
    with:
      Terraform_version: 1.5.7
      Terragrunt_version: 0.53.2
      Working_Directory: envs/dev
      AWS_region: us-east-1
